# Generated by Django 5.0.3 on 2024-03-04 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='name')),
                ('last_name', models.CharField(max_length=20, verbose_name='family')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='address')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('postal_code', models.CharField(max_length=25, verbose_name='postal_code')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
